### ISSUE TITLE
why the map's key must be string?

### ISSUE THREAD

**Issue by iampastor** [streamrail/concurrent-map#11]
Can I set the map's key to interface{}? So I can use any type to be the key.

**Comment by eranchetz** [comment]
Hi @iampastor, 
please see the templating section in the README: https://github.com/streamrail/concurrent-map#templating

Does that answer your question?

**Comment by iampastor** [comment]
@eranchetz thanks a lot, `sed 's/<KEY>/string/g' concurrent_map_template.txt | sed 's/<VAL>/int/g' > cmap_string_int.go` this worked for me.
