### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by alvarolm** [streamrail/concurrent-map#12]
would be nice to have them, keep up the good work, thanks !

**Comment by eranchetz** [comment]
You are more than welcome to add them, we will be waiting for you pull request. 
Thanks for helping us!

**Comment by janisz** [comment]
I created PR for this issue. I'm not an expert in benchmarking so please add your ideas/comments how it should be done

**Comment by eranchetz** [comment]
@janisz Thanks a lot!, we will review it.
