### ISSUE TITLE
How to make a map[string]map[string]chan string?and how to use it?Can you give me some example?

### ISSUE THREAD

**Issue by zkcrescent** [streamrail/concurrent-map#21]

**Comment by eranchetz** [comment]
@zkcrescent Can you give a short example of what you mean, with a regular map (not concurrent)?

**Comment by zkcrescent** [comment]
I've deal it.But now there is a new question:I can't traversal the map.

**Comment by zkcrescent** [comment]
var m = make(map[string]string)
for key,value := range m{
}
how can I do like this?

**Comment by zkcrescent** [comment]
@eranchetz
