### ISSUE TITLE
Concurrent write to different keys from different goroutines

### ISSUE THREAD

**Issue by gnufied** [streamrail/concurrent-map#24]
This is more of a question than a issue. But - lets say each key of Map falls in different shard and each key is being read/written by unique goroutine (i.e - there is a 1:1 mapping between keys and goroutines) - then this implementation implies that we don't need locking.

But in golang 1.6 - if multiple goroutines write to same map even though they all are reading/writing different keys it will result in - "Concurrent write error" and program will crash. 

In fact, I have written a sample program that reproduces this - https://gist.github.com/gnufied/402523b0601f008beb8d627899c73ef8

By this definition - how is this map threadsafe?

**Comment by minecrafter** [comment]
This map is thread-safe because it uses fine-grained locking using shards.
