### ISSUE TITLE
Why the template based generator was removed?

### ISSUE THREAD

**Issue by TamalSaha** [streamrail/concurrent-map#45]
Hi,
I noticed that the template based generator has been removed from this lib. All I could find was this https://github.com/streamrail/concurrent-map/pull/40 . Do you mind elaborating a bit?

I have some code that uses the generated libs from before. So, I am curious.

Thanks.

**Comment by eranchetz** [comment]
1. The template was not updated for a long time and it was hard maintaining
it.
2. The template is only useful for changing the value type, as you cannot
use hashing function on something other than a string key.

Hence it was removed, I think it should be fairly simple to change the code
to support other values other than interface, but I suggest using it
nonetheless.

hope that clarifies the issue
