### ISSUE TITLE
Race conditions using shards

### ISSUE THREAD

**Issue by soluwalana** [streamrail/concurrent-map#6]
Correct me if I'm wrong but isn't there race conditions on lines 63, 109 and 127?
Since you can insert and/or remove items from shards previous or before your current shard in any of those for loops, you can potentially have a conflicting size and your iterator may fewer or more items than were in your cmap at the time of your call.

**Comment by swilly22** [comment]
Correct you are,
line 63 Count function, the value this function returns might be incorrect as items can be removed / added to the map during its execution. it would be reasonable to expect its value to be true until once it returns to its caller not an op code later.

line 109 Iter function, yes indeed, by the time you've processed items of shard #X and moved on to process items of shard #X+1 it might be that items were added / deleted from shard #X, for our usage its good enough. 

line 127 IterBuffered function, well at first this function relies on Count to create its buffered channel so the buffer might be smaller / bigger than the actual map size by the time we're populating the buffer,
suppose that the count function was correct, by the time the function finishes to populate the returned channel the items within the channel might have been removed from the map or new items were introduced to the map, We don't have any grantee on when the caller of InterBuffer will consume the items within the returned channel, once again for the "common" usage: for item := range m.IterBuffered() I think it's good enough.

We could have placed more strict locks, but we feel like it would hurt performance, solutions which maintains performance will be appreciated

**Comment by eranchetz** [comment]
https://github.com/streamrail/concurrent-map/pull/27
