### ISSUE TITLE
error when use with channel

### ISSUE THREAD

**Issue by sdhjl2000** [streamrail/concurrent-map#8]
hi,i use buffer channels as map value for thread safe,when  test use 10 goroutines the value got from channel was not same with the one send in,any suggestion?
```go
testmap := cmap.New()
	fmt.Println("SyncMapNew:    ", TestInParallel(&testmap, 10))
```
```go
func TestInParallel(g *cmap.ConcurrentMap, n int) time.Duration {
	start := time.Now()
	var wait sync.WaitGroup

	for i := 0; i < n; i++ {
		wait.Add(1)
		go func() {
			TheTest(g, rand.New(rand.NewSource(int64(i*500))))
			wait.Done()
		}()
	}
	wait.Wait()
	return time.Now().Sub(start)
}
func TheTest(g *cmap.ConcurrentMap, rnd *rand.Rand) time.Duration {
	start := time.Now()
	var key string
	var value time.Time
	//var got time.Time
	for i := 0; i < 10000; i++ {
		key = strconv.Itoa(int(rnd.Int31n(50000)))
		if g.Has(key) == false {
			g.Set(key, make(chan time.Time, 100))
		}
		tchan, _ := g.Get(key)
		castchan := tchan.(chan time.Time)
		//castchan := make(chan time.Time, 100)
		value = time.Now()
		castchan <- value
		got := <-castchan
		g.Set(key, castchan)
		if value != got {
			panic(fmt.Sprintf("ERROR: expected %v, got %v", value, got))
		}
	}
	return time.Now().Sub(start)
}
```

**Comment by swilly22** [comment]
Hi,

I believe the test is a bit misleading, it is possible for GoRoutine-1 to introduce a new buffered channel under key 'K1' and for another GoRoutine-2 to fetch channel under the same key 'K1'.

At this point both GoRoutines (1, 2) are using the same buffered channel, now imagine that GoRoutine-1 writes to channel and before it's performing a read GoRoutine-2 writes and reads for the same channel, in this case GoRoutine-2 will read the value GoRoutine-1 wrote.

**Comment by sdhjl2000** [comment]
i am not sure buffer channel is thread safe,some one said it is  in this question 
http://stackoverflow.com/questions/10424144/is-it-possible-to-use-gos-buffered-channel-as-a-thread-safe-queue

**Comment by swilly22** [comment]
As far as I know buffered channels are thread safe, with that said, it does not change the misleading behavior of the test you've presented. My explanation see previous comment still stands.
