### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by sammy007** [streamrail/concurrent-map#9]
Got index out of range panic, https://github.com/streamrail/concurrent-map/blob/master/concurrent_map_template.txt#L34

No idea how that happened, afaik it should not.
Marvell PJ4Bv7 Processor rev 2 (v7l)

**Comment by swilly22** [comment]
Hi thanks for reporting,
Could you provide additional information, stderr?

**Comment by sammy007** [comment]
I wrote a test case:

```go
package main

import (
        "hash/fnv"
        "log"
)

func main() {
        hasher := fnv.New32()
        hasher.Write([]byte("abcdef"))
        sum := hasher.Sum32()
        x := int(sum)
        log.Println(sum, x)
}
```

On amd64 result is: <code>2670544664 2670544664</code>
On Marvell PJ4Bv7 Processor rev 2 (v7l) result is: <code>2670544664 -1624422632</code>

So here we fall into index out of range in a GetShard fun.

**Comment by swilly22** [comment]
Nice find!
Unfortunately we don't have this kind of processor, would you mind sending a pull request which deals with this issue?

What value are you getting if you try casting to uint? as this is what we're doing in the GetShard method
return m[uint(hasher.Sum32())%uint(SHARD_COUNT)]

Thank you,

**Comment by jrudio** [comment]
Getting the same `index out of range` error, but only happens when I attach the `cmap.New()` result to a struct and then I try to `.Set()` a value.

If I have the map as a global variable it works flawlessly. 😭
